[package]
name = "tdrs"
version = "0.1.0"
authors = ["Sven van Dam <sven.dam@protonmail.com>"]
edition = "2018"


[dependencies]
structopt = "0.3.7"
serde = { version = "1.0.104" , features = ["derive"]}
serde_json = "1.0.44"
mktemp = "0.4.0"
dirs = "2.0.2"